import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/component/Header";
import { ClerkProvider } from '@clerk/nextjs'
import "@mantine/core/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SNS with Next.js15",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="ja" className="h-full">
        <head>
          <ColorSchemeScript />
        </head>
        <body className={`${inter.className} flex flex-col h-full`}>
          <Header />
          <main className="flex-1 overflow-hidden">
            <MantineProvider>
              {children}
            </MantineProvider>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
